#!/usr/bin/env bun
/**
 * 已迁移手写填空课的共享配置（不属于 `bun test`，由浏览器复验脚本导入）。
 *
 * 一条答案只写一遍：`s2-typed-cdp.ts` 验「空位本身」（出现时机、全角符号、语义写错、
 * 兜底按钮、草稿恢复），`flow-cdp.ts` 验「整课推进」（从 0 推到 N/N 并刷新恢复）。
 * 两个脚本共用这里的答案，改一处两边同时生效，不会各写一份而漂移。
 *
 * 新增课节时在这张表里加一条即可；两个脚本都会自动把它纳入范围。
 */

export type LessonConfig = {
  directory: string;
  storageKey: string;
  micro: string;
  input: string;
  check: string;
  hint: string;
  ref: string;
  reset: string;
  hintPanel: string;
  refPanel: string;
  // 报错写在哪块面板上；不填就是提示面板。S1-02 的报错走流程反馈，提示另有一块。
  feedbackPanel?: string;
  typedField: string;
  draftField: string;
  good: string;
  fullWidth: string;
  fullWidthHint: string;
  outOfBounds: string;
  outOfBoundsMessage: string;
  // 任务 1 里要点对的几处选择；多数课沿用同一套标记，个别课的行名不同，需要逐课声明。
  taskOnePicks?: string[];
  // 点亮「输入框出现」要按的那串按钮；多数课是三步演示，S1-02 这类“存文件 → 编译 → 运行”的课要另写。
  revealButtons?: string[];
  // 只读脚手架所在的行选择器；默认 .code-sheet li，S1-05 用的是 .micro-sheet li。
  scaffoldSelector?: string;
  // 只读脚手架至少要有的行数；默认 2。S1-08 只补一个分号，微练习里就只重复出错那一行。
  scaffoldLines?: number;
  // 两空课的第二空（S1-05 要补 if 与 else if 两行条件）；不填就是常见的单空课。
  secondBlank?: { input: string; good: string };
  scenario: string;
};

// 配置里写 id 的不必再带 #，要写 CSS 选择器的课照写（例如 [data-panel="3"] .micro-sheet）。
export const asSelector = (value: string) => (/^[.#[]/.test(value) ? value : `#${value}`);
export const blankIds = (lesson: LessonConfig) => (lesson.secondBlank ? [lesson.input, lesson.secondBlank.input] : [lesson.input]);

// 已迁移的三十九课各自的答案与应当出现的指正；fullWidth 验全角符号、outOfBounds 验语义写错（越界下标、漏括号、边界写错等）。
export const lessonFlows: LessonConfig[] = [
  {
    directory: "s1-02",
    storageKey: "csp-cpp-s1-02-progress-v1",
    micro: "updateMicro",
    input: "updateInput",
    check: "updateCheckButton",
    hint: "updateHintButton",
    ref: "updateRefButton",
    reset: "updateResetButton",
    hintPanel: "updateHint",
    feedbackPanel: "flowFeedback",
    refPanel: "updateRef",
    typedField: "updateTyped",
    draftField: "updateDraft",
    good: "score = score + 15;",
    fullWidth: "score ＝ score ＋ 15；",
    fullWidthHint: "半角",
    outOfBounds: "score == score + 15;",
    outOfBoundsMessage: "单个 =",
    // 这一课的任务 1 是给三个量选类型，任务 2 是“存文件 → 编译 → 运行”三步，与后续课的三步演示不同。
    taskOnePicks: [
      '[data-quantity="people"] [data-choice="int"]',
      '[data-quantity="average"] [data-choice="double"]',
      '[data-quantity="grade"] [data-choice="char"]',
    ],
    revealButtons: ["saveSourceButton", "compileButton", "runButton"],
    scenario: "写下把 score 加上 15 的更新语句",
  },
  {
    directory: "s1-03",
    storageKey: "csp-cpp-s1-03-progress-v1",
    micro: "avgMicro",
    input: "avgInput",
    check: "avgCheckButton",
    hint: "avgHintButton",
    ref: "avgRefButton",
    reset: "avgResetButton",
    hintPanel: "avgHint",
    // 这一课的报错写在任务 1 共用的反馈区，提示另有一块。
    feedbackPanel: "sourceFeedback",
    refPanel: "avgRef",
    typedField: "avgTyped",
    draftField: "avgDraft",
    good: "(a + b) / 2",
    fullWidth: "（a ＋ b） ／ 2",
    fullWidthHint: "半角",
    outOfBounds: "a + b / 2",
    outOfBoundsMessage: "括号",
    taskOnePicks: ['[data-quantity="perimeter"] [data-choice="grouped"]', '[data-quantity="average"] [data-choice="grouped"]'],
    // 这一课的任务 1 选对公式就直接点亮输入框，没有中间演示按钮。
    revealButtons: [],
    scenario: "写下平均数算式",
  },
  {
    directory: "s1-04",
    storageKey: "csp-cpp-s1-04-progress-v1",
    micro: "cinMicro",
    input: "cinInput",
    check: "cinCheckButton",
    hint: "cinHintButton",
    ref: "cinRefButton",
    reset: "cinResetButton",
    hintPanel: "cinHint",
    feedbackPanel: "sourceFeedback",
    refPanel: "cinRef",
    typedField: "cinTyped",
    draftField: "cinDraft",
    good: "cin >> a >> b;",
    fullWidth: "cin >> a >> b；",
    fullWidthHint: "半角",
    outOfBounds: "cin >> a, b;",
    outOfBoundsMessage: ">>",
    taskOnePicks: ['[data-quantity="twoInts"] [data-choice="chained"]', '[data-quantity="profile"] [data-choice="chained"]'],
    revealButtons: [],
    scenario: "写下一行读入两个整数的语句",
  },
  {
    directory: "s1-05",
    storageKey: "csp-cpp-s1-05-progress-v1",
    // 这一课要补两行条件，空位在任务 4 的面板里，没有单独的 micro 容器 id。
    micro: '[data-panel="3"] .micro-sheet',
    input: "microIf",
    check: "microCheckButton",
    hint: "microHintButton",
    ref: "microRefButton",
    reset: "microResetButton",
    hintPanel: "microFeedback",
    refPanel: "microRef",
    typedField: "microSolved",
    draftField: "microIf",
    scaffoldSelector: ".micro-sheet li",
    secondBlank: { input: "microElseIf", good: "score >= 60" },
    good: "score >= 90",
    fullWidth: "score >= 90；",
    fullWidthHint: "半角",
    outOfBounds: "score > 90",
    outOfBoundsMessage: "包含等于",
    // 三步演示走完只翻到任务 3；任务 3 的 = / == 与括号两处都答对，才会翻到有输入框的面板。
    revealButtons: [
      "divideButton",
      "remainderButton",
      "evenButton",
      '[data-concept="precedence"][data-pick="divide-first"]',
      '[data-concept="parens"][data-pick="grouped"]',
    ],
    scenario: "亲手补齐优秀与合格两行条件",
  },
  {
    directory: "s1-06",
    storageKey: "csp-cpp-s1-06-progress-v1",
    micro: "loopMicro",
    input: "loopInput",
    check: "loopCheckButton",
    hint: "loopHintButton",
    ref: "loopRefButton",
    reset: "loopResetButton",
    hintPanel: "loopHint",
    feedbackPanel: "sourceFeedback",
    refPanel: "loopRef",
    typedField: "loopTyped",
    draftField: "loopDraft",
    good: "for (int i = 1; i <= n; i++)",
    fullWidth: "for（int i ＝ 1； i ＜＝ n； i＋＋）",
    fullWidthHint: "半角",
    outOfBounds: "for (int i = 1; i < n; i++)",
    outOfBoundsMessage: "n 也要进去",
    revealButtons: [],
    scenario: "写下从 1 数到 n 的循环表头",
  },
  {
    directory: "s1-07",
    storageKey: "csp-cpp-s1-07-progress-v1",
    micro: "colMicro",
    input: "colInput",
    check: "colCheckButton",
    hint: "colHintButton",
    ref: "colRefButton",
    reset: "colResetButton",
    hintPanel: "colHint",
    feedbackPanel: "sourceFeedback",
    refPanel: "colRef",
    typedField: "colTyped",
    draftField: "colDraft",
    good: "for (int c = 1; c <= n; c++)",
    fullWidth: "for（int c ＝ 1； c ＜＝ n； c＋＋）",
    fullWidthHint: "半角",
    outOfBounds: "for (int r = 1; r <= n; r++)",
    outOfBoundsMessage: "内层管列",
    revealButtons: [],
    scenario: "写下管列的内层循环",
  },
  {
    directory: "s1-08",
    storageKey: "csp-cpp-s1-08-progress-v1",
    micro: "semiMicro",
    input: "semiInput",
    check: "semiCheckButton",
    hint: "semiHintButton",
    ref: "semiRefButton",
    reset: "semiResetButton",
    hintPanel: "semiHint",
    // 这一课报错沿用定位步骤的流程反馈区。
    feedbackPanel: "flowFeedback",
    refPanel: "semiRef",
    // 这一课只补一个分号：微练习里只重复出错的那一行，完整四行程序在任务 1 已经读过。
    scaffoldLines: 1,
    typedField: "semiTyped",
    draftField: "semiDraft",
    good: ";",
    fullWidth: "；",
    fullWidthHint: "半角",
    outOfBounds: ";n",
    outOfBoundsMessage: "一个分号",
    scenario: "补上漏掉的那一个分号",
  },
  {
    directory: "s2-01",
    storageKey: "csp-cpp-s2-01-progress-v1",
    micro: "lastIndexMicro",
    input: "lastIndexInput",
    check: "lastIndexCheckButton",
    hint: "lastIndexHintButton",
    ref: "lastIndexRefButton",
    reset: "lastIndexResetButton",
    hintPanel: "lastIndexHint",
    refPanel: "lastIndexRef",
    typedField: "lastIndexTyped",
    draftField: "lastIndexDraft",
    good: "a[n - 1]",
    fullWidth: "a［n - 1］",
    fullWidthHint: "半角",
    outOfBounds: "a[n]",
    outOfBoundsMessage: "越界",
    scenario: "访问最后一个成绩",
  },
  {
    directory: "s2-02",
    storageKey: "csp-cpp-s2-02-progress-v1",
    micro: "lastCharMicro",
    input: "lastCharInput",
    check: "lastCharCheckButton",
    hint: "lastCharHintButton",
    ref: "lastCharRefButton",
    reset: "lastCharResetButton",
    hintPanel: "lastCharHint",
    refPanel: "lastCharRef",
    typedField: "lastCharTyped",
    draftField: "lastCharDraft",
    good: "s[n - 1]",
    fullWidth: "s［n - 1］",
    fullWidthHint: "半角",
    outOfBounds: "s[n]",
    outOfBoundsMessage: "越界",
    scenario: "访问最后一个字符",
  },
  {
    directory: "s2-03",
    storageKey: "csp-cpp-s2-03-progress-v1",
    micro: "callMicro",
    input: "callInput",
    check: "callCheckButton",
    hint: "callHintButton",
    ref: "callRefButton",
    reset: "callResetButton",
    hintPanel: "callHint",
    refPanel: "callRef",
    typedField: "callTyped",
    draftField: "callDraft",
    good: "isEven(4)",
    fullWidth: "isEven（4）",
    fullWidthHint: "半角",
    outOfBounds: "isEven",
    outOfBoundsMessage: "括号",
    scenario: "写出这次调用",
  },
  {
    directory: "s2-04",
    storageKey: "csp-cpp-s2-04-progress-v1",
    micro: "passParamMicro",
    input: "passParamInput",
    check: "passParamCheckButton",
    hint: "passParamHintButton",
    ref: "passParamRefButton",
    reset: "passParamResetButton",
    hintPanel: "passParamHint",
    refPanel: "passParamRef",
    typedField: "passParamTyped",
    draftField: "passParamDraft",
    good: "int x",
    fullWidth: "int x；",
    fullWidthHint: "半角",
    outOfBounds: "int &x",
    outOfBoundsMessage: "引用",
    scenario: "写出值传递的形参",
  },
  {
    directory: "s2-05",
    storageKey: "csp-cpp-s2-05-progress-v1",
    micro: "memberMicro",
    input: "memberInput",
    check: "memberCheckButton",
    hint: "memberHintButton",
    ref: "memberRefButton",
    reset: "memberResetButton",
    hintPanel: "memberHint",
    refPanel: "memberRef",
    typedField: "memberTyped",
    draftField: "memberDraft",
    good: "a[0].score",
    fullWidth: "a[0]．score",
    fullWidthHint: "半角",
    outOfBounds: "a[0].name",
    outOfBoundsMessage: "score",
    scenario: "写出读分数的成员访问",
  },
  {
    directory: "s2-06",
    storageKey: "csp-cpp-s2-06-progress-v1",
    micro: "swapMicro",
    input: "swapInput",
    check: "swapCheckButton",
    hint: "swapHintButton",
    ref: "swapRefButton",
    reset: "swapResetButton",
    hintPanel: "swapHint",
    refPanel: "swapRef",
    typedField: "swapTyped",
    draftField: "swapDraft",
    good: "swap(a[0], a[1])",
    fullWidth: "swap（a[0], a[1]）",
    fullWidthHint: "半角",
    outOfBounds: "swap(a[0], a[2])",
    outOfBoundsMessage: "相邻",
    scenario: "写出相邻交换",
  },
  {
    directory: "s2-07",
    storageKey: "csp-cpp-s2-07-progress-v1",
    micro: "enumMicro",
    input: "enumInput",
    check: "enumCheckButton",
    hint: "enumHintButton",
    ref: "enumRefButton",
    reset: "enumResetButton",
    hintPanel: "enumHint",
    refPanel: "enumRef",
    typedField: "enumTyped",
    draftField: "enumDraft",
    good: "if (i % 2 == 0) evenCount++;",
    fullWidth: "if（i ％ 2 == 0）evenCount＋＋；",
    fullWidthHint: "半角",
    outOfBounds: "evenCount++;",
    outOfBoundsMessage: "漏分支",
    scenario: "写出遇到偶数时的判断与更新",
  },
  {
    directory: "s2-08",
    storageKey: "csp-cpp-s2-08-progress-v1",
    micro: "opsMicro",
    input: "opsInput",
    check: "opsCheckButton",
    hint: "opsHintButton",
    ref: "opsRefButton",
    reset: "opsResetButton",
    hintPanel: "opsHint",
    refPanel: "opsRef",
    typedField: "opsTyped",
    draftField: "opsDraft",
    good: "n * n",
    fullWidth: "n ＊ n",
    fullWidthHint: "半角",
    outOfBounds: "n + n",
    outOfBoundsMessage: "相乘",
    scenario: "写出双层循环的次数算式",
  },
  {
    directory: "s3-01",
    storageKey: "csp-cpp-s3-01-progress-v1",
    micro: "digitMicro",
    input: "digitInput",
    check: "digitCheckButton",
    hint: "digitHintButton",
    ref: "digitRefButton",
    reset: "digitResetButton",
    hintPanel: "digitHint",
    refPanel: "digitRef",
    typedField: "digitTyped",
    draftField: "digitDraft",
    good: "x % 10",
    fullWidth: "x ％ 10",
    fullWidthHint: "半角",
    outOfBounds: "x / 10",
    outOfBoundsMessage: "去掉个位",
    scenario: "写出取出十进制个位的算式",
  },
  {
    directory: "s3-02",
    storageKey: "csp-cpp-s3-02-progress-v1",
    micro: "factMicro",
    input: "factInput",
    check: "factCheckButton",
    hint: "factHintButton",
    ref: "factRefButton",
    reset: "factResetButton",
    hintPanel: "factHint",
    refPanel: "factRef",
    typedField: "factTyped",
    draftField: "factDraft",
    good: "n * fact(n - 1)",
    fullWidth: "n ＊ fact（n - 1）",
    fullWidthHint: "半角",
    outOfBounds: "n * fact(n)",
    outOfBoundsMessage: "边界",
    scenario: "写出阶乘的递归调用",
  },
  {
    directory: "s3-03",
    storageKey: "csp-cpp-s3-03-progress-v1",
    micro: "midMicro",
    input: "midInput",
    check: "midCheckButton",
    hint: "midHintButton",
    ref: "midRefButton",
    reset: "midResetButton",
    hintPanel: "midHint",
    refPanel: "midRef",
    typedField: "midTyped",
    draftField: "midDraft",
    good: "(left + right) / 2",
    fullWidth: "（left ＋ right）／ 2",
    fullWidthHint: "半角",
    outOfBounds: "left + right / 2",
    outOfBoundsMessage: "少了括号",
    scenario: "写出二分的中点算式",
  },
  {
    directory: "s3-04",
    storageKey: "csp-cpp-s3-04-progress-v1",
    micro: "prefixMicro",
    input: "prefixInput",
    check: "prefixCheckButton",
    hint: "prefixHintButton",
    ref: "prefixRefButton",
    reset: "prefixResetButton",
    hintPanel: "prefixHint",
    refPanel: "prefixRef",
    typedField: "prefixTyped",
    draftField: "prefixDraft",
    good: "sum[i] = sum[i - 1] + a[i]",
    fullWidth: "sum［i］ ＝ sum［i － 1］ ＋ a［i］",
    fullWidthHint: "半角",
    outOfBounds: "sum[i] = sum[i] + a[i]",
    outOfBoundsMessage: "少减了",
    scenario: "写出填表（前缀和）语句",
  },
  {
    directory: "s3-05",
    storageKey: "csp-cpp-s3-05-progress-v1",
    micro: "windowMicro",
    input: "windowInput",
    check: "windowCheckButton",
    hint: "windowHintButton",
    ref: "windowRefButton",
    reset: "windowResetButton",
    hintPanel: "windowHint",
    refPanel: "windowRef",
    typedField: "windowTyped",
    draftField: "windowDraft",
    good: "right++; sum += a[right];",
    fullWidth: "right＋＋； sum ＋= a［right］；",
    fullWidthHint: "半角",
    outOfBounds: "sum += a[right]; right++;",
    outOfBoundsMessage: "顺序反了",
    scenario: "写出扩大窗口的两步",
  },
  {
    directory: "s3-06",
    storageKey: "csp-cpp-s3-06-progress-v1",
    micro: "greedyMicro",
    input: "greedyInput",
    check: "greedyCheckButton",
    hint: "greedyHintButton",
    ref: "greedyRefButton",
    reset: "greedyResetButton",
    hintPanel: "greedyHint",
    refPanel: "greedyRef",
    typedField: "greedyTyped",
    draftField: "greedyDraft",
    good: "sort(a + 1, a + 4, by_end)",
    fullWidth: "sort（a ＋ 1， a ＋ 4， by_end）",
    fullWidthHint: "半角",
    outOfBounds: "sort(a + 1, a + 4, by_start)",
    outOfBoundsMessage: "开始时间",
    scenario: "写出按结束时间排序的那一行",
  },
  {
    directory: "s3-07",
    storageKey: "csp-cpp-s3-07-progress-v1",
    micro: "stackMicro",
    input: "stackInput",
    check: "stackCheckButton",
    hint: "stackHintButton",
    ref: "stackRefButton",
    reset: "stackResetButton",
    hintPanel: "stackHint",
    refPanel: "stackRef",
    typedField: "stackTyped",
    draftField: "stackDraft",
    good: "st.pop()",
    fullWidth: "st．pop（）",
    fullWidthHint: "半角",
    outOfBounds: "st.top()",
    outOfBoundsMessage: "看一眼",
    scenario: "写出配对成功后弹掉栈顶的那一行",
  },
  {
    directory: "s3-08",
    storageKey: "csp-cpp-s3-08-progress-v1",
    micro: "dpMicro",
    input: "dpInput",
    check: "dpCheckButton",
    hint: "dpHintButton",
    ref: "dpRefButton",
    reset: "dpResetButton",
    hintPanel: "dpHint",
    refPanel: "dpRef",
    typedField: "dpTyped",
    draftField: "dpDraft",
    good: "dp[i] = dp[i - 1] + dp[i - 2]",
    fullWidth: "dp［i］＝dp［i － 1］＋dp［i － 2］",
    fullWidthHint: "半角",
    outOfBounds: "dp[i] = dp[i - 1] * dp[i - 2]",
    outOfBoundsMessage: "相加",
    scenario: "写出爬楼梯的转移那一行",
  },
  {
    directory: "s4-01",
    storageKey: "csp-cpp-s4-01-progress-v1",
    micro: "outputMicro",
    input: "outputInput",
    check: "outputCheckButton",
    hint: "outputHintButton",
    ref: "outputRefButton",
    reset: "outputResetButton",
    hintPanel: "outputHint",
    refPanel: "outputRef",
    typedField: "outputTyped",
    draftField: "outputDraft",
    good: "cout << n + 1;",
    fullWidth: "cout ＜＜ n ＋ 1；",
    fullWidthHint: "半角",
    outOfBounds: "cin >> n + 1;",
    outOfBoundsMessage: "cin",
    scenario: "写出只输出答案的那一行",
  },
  {
    directory: "s4-02",
    storageKey: "csp-cpp-s4-02-progress-v1",
    micro: "sumMicro",
    input: "sumInput",
    check: "sumCheckButton",
    hint: "sumHintButton",
    ref: "sumRefButton",
    reset: "sumResetButton",
    hintPanel: "sumHint",
    refPanel: "sumRef",
    typedField: "sumTyped",
    draftField: "sumDraft",
    good: "sum += a[i];",
    fullWidth: "sum ＋= a［i］；",
    fullWidthHint: "半角",
    outOfBounds: "sum = a[i];",
    outOfBoundsMessage: "覆盖",
    scenario: "写出把当前这个数累加进 sum 的那一行",
  },
  {
    directory: "s4-03",
    storageKey: "csp-cpp-s4-03-progress-v1",
    micro: "guardMicro",
    input: "guardInput",
    check: "guardCheckButton",
    hint: "guardHintButton",
    ref: "guardRefButton",
    reset: "guardResetButton",
    hintPanel: "guardHint",
    refPanel: "guardRef",
    typedField: "guardTyped",
    draftField: "guardDraft",
    good: "if (balance + x >= 0)",
    fullWidth: "if （balance ＋ x ＞= 0）",
    fullWidthHint: "半角",
    outOfBounds: "if (balance + x > 0)",
    outOfBoundsMessage: "刚好",
    scenario: "写出判断这次操作能不能做的那一行",
  },
  {
    directory: "s4-04",
    storageKey: "csp-cpp-s4-04-progress-v1",
    micro: "pruneMicro",
    input: "pruneInput",
    check: "pruneCheckButton",
    hint: "pruneHintButton",
    ref: "pruneRefButton",
    reset: "pruneResetButton",
    hintPanel: "pruneHint",
    refPanel: "pruneRef",
    typedField: "pruneTyped",
    draftField: "pruneDraft",
    good: "if (sum > target) return;",
    fullWidth: "if （sum ＞ target） return；",
    fullWidthHint: "半角",
    outOfBounds: "if (sum >= target) return;",
    outOfBoundsMessage: "边界差一点",
    scenario: "写出剪枝那一行",
  },
  {
    directory: "s4-05",
    storageKey: "csp-cpp-s4-05-progress-v1",
    micro: "countMicro",
    input: "countInput",
    check: "countCheckButton",
    hint: "countHintButton",
    ref: "countRefButton",
    reset: "countResetButton",
    hintPanel: "countHint",
    refPanel: "countRef",
    typedField: "countTyped",
    draftField: "countDraft",
    good: "cnt[score]++;",
    fullWidth: "cnt［score］＋＋；",
    fullWidthHint: "半角",
    outOfBounds: "cnt[score] = 1;",
    outOfBoundsMessage: "覆盖",
    taskOnePicks: ['[data-quantity="rangeTool"] [data-choice="counting"]', '[data-quantity="dupTool"] [data-choice="sortScan"]'],
    scenario: "写出把这次读到的分数记进计数数组的那一行",
  },
  {
    directory: "s4-06",
    storageKey: "csp-cpp-s4-06-progress-v1",
    micro: "transitionMicro",
    input: "transitionInput",
    check: "transitionCheckButton",
    hint: "transitionHintButton",
    ref: "transitionRefButton",
    reset: "transitionResetButton",
    hintPanel: "transitionHint",
    refPanel: "transitionRef",
    typedField: "transitionTyped",
    draftField: "transitionDraft",
    good: "dp[i] = max(dp[i - 1], dp[i - 2] + nums[i]);",
    fullWidth: "dp［i］＝max（dp［i－1］，dp［i－2］＋nums［i］）；",
    fullWidthHint: "半角",
    outOfBounds: "dp[i] = max(dp[i - 1], dp[i - 2]);",
    outOfBoundsMessage: "少了金额",
    taskOnePicks: ['[data-quantity="stateTool"] [data-choice="define-dp"]', '[data-quantity="pickTool"] [data-choice="pick-or-skip"]'],
    scenario: "写出打家劫舍的转移那一行",
  },
  {
    directory: "s4-07",
    storageKey: "csp-cpp-s4-07-progress-v1",
    micro: "guardMicro",
    input: "guardInput",
    check: "guardCheckButton",
    hint: "guardHintButton",
    ref: "guardRefButton",
    reset: "guardResetButton",
    hintPanel: "guardHint",
    refPanel: "guardRef",
    typedField: "guardTyped",
    draftField: "guardDraft",
    good: "if (visited[u]) return;",
    fullWidth: "if（visited［u］）return；",
    fullWidthHint: "半角",
    outOfBounds: "if (!visited[u]) return;",
    outOfBoundsMessage: "写反",
    taskOnePicks: ['[data-quantity="graphTool"] [data-choice="adjacency-list"]', '[data-quantity="visitedTool"] [data-choice="visited-array"]'],
    scenario: "写出 dfs 防止重复访问的那一行",
  },
  {
    directory: "s4-08",
    storageKey: "csp-cpp-s4-08-progress-v1",
    micro: "fallbackMicro",
    input: "fallbackInput",
    check: "fallbackCheckButton",
    hint: "fallbackHintButton",
    ref: "fallbackRefButton",
    reset: "fallbackResetButton",
    hintPanel: "fallbackHint",
    refPanel: "fallbackRef",
    typedField: "fallbackTyped",
    draftField: "fallbackDraft",
    good: "if (n <= 1000) { cout << brute(n); return 0; }",
    fullWidth: "if（n ＜= 1000）｛cout ＜＜ brute（n）；return 0；｝",
    fullWidthHint: "半角",
    outOfBounds: "if (n <= 100000) { cout << brute(n); return 0; }",
    outOfBoundsMessage: "10 万",
    taskOnePicks: ['[data-quantity="orderChoice"] [data-choice="brute-first"]', '[data-quantity="fallbackChoice"] [data-choice="submit-fallback"]'],
    scenario: "写出子任务 1 的保底分支那一行",
  },
  {
    directory: "s5-02",
    storageKey: "csp-cpp-s5-02-progress-v1",
    micro: "debugPrintMicro",
    input: "debugPrintInput",
    check: "debugPrintCheckButton",
    hint: "debugPrintHintButton",
    ref: "debugPrintRefButton",
    reset: "debugPrintResetButton",
    hintPanel: "debugPrintHint",
    refPanel: "debugPrintRef",
    typedField: "debugPrintTyped",
    draftField: "debugPrintDraft",
    good: 'cout << i << " " << prefix;',
    fullWidth: 'cout ＜＜ i ＜＜ " " ＜＜ prefix；',
    fullWidthHint: "半角",
    outOfBounds: "cin >> i >> prefix;",
    outOfBoundsMessage: "读入",
    taskOnePicks: [
      '[data-quantity="orderChoice"] [data-choice="brute-first"]',
      '[data-quantity="fallbackChoice"] [data-choice="submit-fallback"]',
    ],
    scenario: "写出循环里的分段输出那一行",
  },
  {
    directory: "s5-03",
    storageKey: "csp-cpp-s5-03-progress-v1",
    micro: "sumTypeMicro",
    input: "sumTypeInput",
    check: "sumTypeCheckButton",
    hint: "sumTypeHintButton",
    ref: "sumTypeRefButton",
    reset: "sumTypeResetButton",
    hintPanel: "sumTypeHint",
    refPanel: "sumTypeRef",
    typedField: "sumTypeTyped",
    draftField: "sumTypeDraft",
    good: "long long sum = 0;",
    fullWidth: "long long sum ＝ 0；",
    fullWidthHint: "半角",
    outOfBounds: "int sum = 0;",
    outOfBoundsMessage: "装不下",
    taskOnePicks: [
      '[data-quantity="overflowChoice"] [data-choice="is-overflow"]',
      '[data-quantity="boundsChoice"] [data-choice="is-bounds"]',
    ],
    scenario: "写出累加变量的那一行声明",
  },
  {
    directory: "s5-04",
    storageKey: "csp-cpp-s5-04-progress-v1",
    micro: "rangeQueryMicro",
    input: "rangeQueryInput",
    check: "rangeQueryCheckButton",
    hint: "rangeQueryHintButton",
    ref: "rangeQueryRefButton",
    reset: "rangeQueryResetButton",
    hintPanel: "rangeQueryHint",
    refPanel: "rangeQueryRef",
    typedField: "rangeQueryTyped",
    draftField: "rangeQueryDraft",
    good: "sum[r] - sum[l - 1]",
    fullWidth: "sum［r］－sum［l－1］",
    fullWidthHint: "半角",
    outOfBounds: "sum[r] - sum[l]",
    outOfBoundsMessage: "伪优化",
    taskOnePicks: [
      '[data-quantity="startChoice"] [data-choice="write-baseline"]',
      '[data-quantity="labelChoice"] [data-choice="label-limits"]',
    ],
    scenario: "写出升级后区间和的那一个算式",
  },
  {
    directory: "s5-05",
    storageKey: "csp-cpp-s5-05-progress-v1",
    micro: "emptyGuardMicro",
    input: "emptyGuardInput",
    check: "emptyGuardCheckButton",
    hint: "emptyGuardHintButton",
    ref: "emptyGuardRefButton",
    reset: "emptyGuardResetButton",
    hintPanel: "emptyGuardHint",
    refPanel: "emptyGuardRef",
    typedField: "emptyGuardTyped",
    draftField: "emptyGuardDraft",
    good: 'if (n == 0) { cout << 0 << "\\n"; return 0; }',
    fullWidth: 'if （n ＝＝ 0） ｛ cout ＜＜ 0 ＜＜ "\\n"； return 0； ｝',
    fullWidthHint: "半角",
    outOfBounds: 'if (n == 1) { cout << 0 << "\\n"; return 0; }',
    outOfBoundsMessage: "n=0",
    taskOnePicks: [
      '[data-quantity="startChoice"] [data-choice="scan-and-order"]',
      '[data-quantity="labelChoice"] [data-choice="log-self-test"]',
    ],
    scenario: "写出空数据时输出 0 并结束的那一段",
  },
  {
    directory: "s5-06",
    storageKey: "csp-cpp-s5-06-progress-v1",
    micro: "loopBoundMicro",
    input: "loopBoundInput",
    check: "loopBoundCheckButton",
    hint: "loopBoundHintButton",
    ref: "loopBoundRefButton",
    reset: "loopBoundResetButton",
    hintPanel: "loopBoundHint",
    refPanel: "loopBoundRef",
    typedField: "loopBoundTyped",
    draftField: "loopBoundDraft",
    good: "i <= n",
    fullWidth: "i ＜= n",
    fullWidthHint: "半角",
    outOfBounds: "i < n",
    outOfBoundsMessage: "最后一个",
    taskOnePicks: [
      '[data-quantity="startChoice"] [data-choice="classify-first"]',
      '[data-quantity="actionChoice"] [data-choice="write-fix-rule"]',
    ],
    scenario: "写出让循环走到最后一个下标的那一个条件",
  },
  {
    directory: "s5-01",
    storageKey: "csp-cpp-s5-01-progress-v1",
    micro: "arraySizeMicro",
    input: "arraySizeInput",
    check: "arraySizeCheckButton",
    hint: "arraySizeHintButton",
    ref: "arraySizeRefButton",
    reset: "arraySizeResetButton",
    hintPanel: "arraySizeHint",
    refPanel: "arraySizeRef",
    typedField: "arraySizeTyped",
    draftField: "arraySizeDraft",
    good: "int a[100005];",
    fullWidth: "int a［100005］；",
    fullWidthHint: "半角",
    outOfBounds: "int a[100000];",
    outOfBoundsMessage: "越界",
    taskOnePicks: [
      '[data-quantity="orderChoice"] [data-choice="brute-first"]',
      '[data-quantity="fallbackChoice"] [data-choice="submit-fallback"]',
    ],
    scenario: "按审题圈出的数据范围写出数组那一行",
  },
  {
    directory: "s5-07",
    storageKey: "csp-cpp-s5-07-progress-v1",
    micro: "crossCheckMicro",
    input: "crossCheckInput",
    check: "crossCheckCheckButton",
    hint: "crossCheckHintButton",
    ref: "crossCheckRefButton",
    reset: "crossCheckResetButton",
    hintPanel: "crossCheckHint",
    refPanel: "crossCheckRef",
    typedField: "crossCheckTyped",
    draftField: "crossCheckDraft",
    good: "long long formula = 1LL * n * (n + 1) / 2;",
    fullWidth: "long long formula ＝ 1LL ＊ n ＊ （n ＋ 1） ／ 2；",
    fullWidthHint: "半角",
    outOfBounds: "long long formula = n * (n + 1) / 2;",
    outOfBoundsMessage: "溢出",
    taskOnePicks: [
      '[data-quantity="startChoice"] [data-choice="bring-last-habit"]',
      '[data-quantity="labelChoice"] [data-choice="cross-check-twice"]',
    ],
    scenario: "写出交叉检查时独立再算一遍的那一行",
  },
  {
    directory: "s5-08",
    storageKey: "csp-cpp-s5-08-progress-v1",
    micro: "arrayInitMicro",
    input: "arrayInitInput",
    check: "arrayInitCheckButton",
    hint: "arrayInitHintButton",
    ref: "arrayInitRefButton",
    reset: "arrayInitResetButton",
    hintPanel: "arrayInitHint",
    refPanel: "arrayInitRef",
    typedField: "arrayInitTyped",
    draftField: "arrayInitDraft",
    good: "int cnt[105] = {0};",
    fullWidth: "int cnt［105］ ＝ ｛0｝；",
    fullWidthHint: "半角",
    outOfBounds: "int cnt[105] = 0;",
    outOfBoundsMessage: "第一个格子",
    taskOnePicks: [
      '[data-quantity="startChoice"] [data-choice="list-and-rate"]',
      '[data-quantity="labelChoice"] [data-choice="specific-topic-with-plan"]',
    ],
    scenario: "写出赛前清单里计数数组清零的那一行",
  },
];
